### ISSUE TITLE
V3: Mocking location data to test Prismic Previews

### ISSUE THREAD

**Issue by TatsumiSuenaga** [prismicio/prismic-gatsby#182]
Hello, I was wondering if anyone has successfully tested their preview pages with passing mock data.
Currently with Cypress, I am trying to re-enact a user using previews by passing a mocked `location` object to my preview page. Sadly my mocked location data is not recognized by the `usePrismicPreview` hook. I have tried copying over the `location` object from an actual preview, but I am not getting the right data from the hook.

Does anyone have any recommendations? By the way, the schema of my `location` object is below.
```
{
        href: 'http://localhost:8000/preview/?token=blah',
        origin: 'http://localhost:8000',
        protocol: "http:",
        host: "localhost:8000",
        hostname: "localhost",
        port: "8000",
        pathname: "/preview/",
        search:"?token=blah",
        hash: "",
        state: null,
        key: "initial"
};
```

Also my dependency versions:
```
"gatsby-source-prismic": "^3.0.0-beta.19"
...
"cypress": "^3.8.1"
```

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!

FYI previews should be handled using `gatsby-plugin-prismic-previews`. It uses `@prismicio/client` to load previews automatically which reads from `window.location`. You should be able to mock the global `window.location` if you need to manually control this flow.
