### ISSUE TITLE
v3: Reducing Bundle Size by 80kb | remove yup & lodash from webpack bundles

### ISSUE THREAD

**Issue by rubas** [prismicio/prismic-gatsby#185]
I noticed that we end up with `yup/lib` and `lodash` in our webpack bundles, while using `gatsby-source-prismic`.

We don't need `yup` or `lodash` and `npm ls yup` points me only to `gatsby-source-prismic`.

`yup` is used to [`validatePluginOptions`](https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/src/common/validatePluginOptions.js#L6). It should not find its way it to production webpack bundles.

Ignoring this module in webpack saves us another 80kb  🍾 

Sadly this **breaks** the sites, as the validation code is executed again in this stage of the build process?! Maybe you have a better idea ... let's get rid of that bloat.

## How to ignore it ...
Just add the following to your `gatsby-node.js`
```
exports.onCreateWebpackConfig = ({ stage, actions }) => {
  actions.setWebpackConfig({
    plugins: stage === "build-javascript" ? [new webpack.IgnorePlugin(/yup/)] : [],
  })
```

## How to test it ...
use `webpack-bundle-analyzer` in your `gatsby-config.js`

```
    {
      resolve: `gatsby-plugin-webpack-bundle-analyser-v2`,
      options: {
        analyzerMode: `server`,
        analyzerPort: `3001`,
        disable: !process.env.DEBUG == "1", // run with `DEBUG=1 yarn build`
      },
    },
```

**Comment by angeloashmore** [comment]
Hey @rubas, thanks for pointing this out. The plugins are validated again in the browser via `gatsby-browser.js` to ensure the preview hook has valid data to work with.

While converting the project to TypeScript in `v3-beta-ts`, I realized there is no need to revalidate the plugin options since they are already validated in `gatsby-node.js`. Both the source plugin and preview hook need to validate options, however, so Yup was replaced with Superstruct.

https://github.com/angeloashmore/gatsby-source-prismic/blob/6cc5888811ac1e42215827ee5a96a719855551a2/src/validateOptions.ts

`v3.0.0-beta.24` includes these changes.

The next bundle size savings we can get is changing from `prismic-dom` to the lower-level `prismic-helpers` and `prismic-richtext`.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!

The latest version of the plugin uses a different architecture. Reducing the bundle size is on the roadmap for the new plugin as well.
