### ISSUE TITLE
V3.0.0-beta.26 has previewData linked documents as Proxy array empty

### ISSUE THREAD

**Issue by ahmedghazi** [prismicio/prismic-gatsby#207]
When i test the website into preview mode, i get the data, but the slices or content relationship don't have the same model. The data is of type "Proxy".

How can i get the data as in the non preview? Is there a serialzer to use?

Here is a screenshot of my console.

<img width="637" alt="Capture d’écran 2020-03-26 à 13 46 28" src="https://user-images.githubusercontent.com/3919985/77648431-6df0c900-6f68-11ea-9ede-c90af76ab846.png">

Another example here with my categories reference. There is a Proxy array but the document becomes a string. 
<img width="646" alt="Capture d’écran 2020-03-26 à 14 37 16" src="https://user-images.githubusercontent.com/3919985/77653156-b2cc2e00-6f6f-11ea-9343-a7dc00f55339.png">

It says in the documentation 
> If previewData contains a document nested in staticData: Returns a new object with the nested document replaced anywhere it is referenced. Note that this only works if the nested data in staticData includes the document's ID field. This is useful for previewing documents whose data is only a smaller part of a whole page.
> 

I do give ids to my nested document but still i get an empty response
```javascript
				tags {
					tag {
						id
						type
						document {
							... on PrismicCategorieBlog {
								id
								uid
								href
								dataString
								data {
									title {
										text
									}
								}
							}
						}
					}
				}
```

**Comment by angeloashmore** [comment]
Hi @ahmedghazi, the Proxy is used to handle document relationships. Relationship fields only contain the ID of the document, as you can see in the `document` field. When you access that property, however, the Proxy handles converting that ID to the document node.

If you log `previewData.prismicHome.data.body[0]`, you should see the first slice object.

**Comment by ahmedghazi** [comment]
Hi @angeloashmore thx for the reply.
I got the slices to work fine :). 
However the nested content relationship still doesn't.
Example my categories are not populated as usual. The document field is just an id, no data inside.
<img width="531" alt="Capture d’écran 2020-03-27 à 11 19 57" src="https://user-images.githubusercontent.com/3919985/77746272-fb8df080-701c-11ea-976d-d686eb03ff73.png">

**Comment by angeloashmore** [comment]
@ahmedghazi I think you found a bug. Looks like this like should be `await`ed, but is not: https://github.com/angeloashmore/gatsby-source-prismic/blob/882a5a41daac14e1caea039277cb876d97ae8a1c/src/environment.browser.ts#L129

It's possible the link normalizer is returning before the linked document is fetched so the proxy doesn't see the link.

I'll try to find time to patch this, but also happy to review a PR.

**Comment by ahmedghazi** [comment]
Oh Ok.
Reminds me that i had an issue prior, in preview.js page the previewData and path were undefined.
I had to test all the variables returned from usePrismicPreview until they are populated to launch the navigate
```javascript
useEffect(() => {
    // If this is not a preview, skip.
    //   null = Not yet determined if previewing.
    //   true = Preview is available.
    //   false = Preview is not available.
    if (isPreview === false 
      || isPreview === undefined
      || previewData === undefined 
      || path === undefined) return
    // if (previewData === undefined || path === undefined) return
    // console.log("previewData", previewData)

    window.__PRISMIC_PREVIEW_DATA__ = previewData
    // console.log(previewData)

    // Navigate to the document's page.
    navigate(path)
  }, [isPreview, isLoading, previewData, path])
```

**Comment by kb1995** [comment]
@angeloashmore Did you find a solution for this? Even though I'm in the process of migrating to v4, I started experiencing this problem when previewing documents in v3

**Comment by valtism** [comment]
@kb1995 I encountered this problem recently, and I decided that accessing different types through a content relationship (via `.document`) was probably an anti-pattern. It was already giving me headaches in TypeScript because I could not type narrow down to the exact type of link it was.

What I did to fix it was to remove any and all `.document` calls and instead query the document type itself, sometimes filtering, using GraphQL variables.

I'll give an example of what I did below. In my case, I was using `.document` to link an `Author` custom type to a `BlogPage` custom type, linked via a group of Content Relationships in the BlogPage.

For me, this meant changing a query like this:

```graphql
query blogPageQuery($uid: String) {
  prismicBlogPage(uid: { eq: $uid }) {
    uid
    url
    data {
      title {
        text
      }
      content {
        raw
      }
      authors {
        author {
          document {
            ... on PrismicAuthor {
              id
              data {
                first_name {
                  text
                }
              }
            }
          }
        }
      }
    }
  }
}
```

to something like this 

```graphql
query blogPageQuery($uid: String, $authorIds: [ID]) {
  prismicBlogPage(uid: { eq: $uid }) {
    uid
    url
    data {
      title {
        text
      }
      content {
        raw
      }
    }
  }
  allPrismicAuthor(filter: { prismicId: { in: $authorIds } }) {
    nodes {
      id
      data {
        first_name {
          text
        }
      }
    }
  }
}
```

Note that in the second query, we are getting the authors using `allPrismicAuthor` using the filter `$authorIds: [ID]`.

In order to get the variable `$authorIds`, we need to pass it to the pageContext in `gatsby-node.js`. That meant adding a query for the authors in the top-level node query

```graphql
{
  allPrismicBlogPage {
    nodes {
      id
      uid
      type
      url
      data {
        authors {
          author {
            id
          }
        }
      }
    }
  }
}
```

and then passing it into the `createPage` context like so:

```js
pages.data.allPrismicBlogPage.nodes.forEach((page) => {
  createPage({
    path: page.url,
    component: path.resolve(__dirname, 'src/templates/BlogPage.tsx'),
    context: {
      authorIds: page.data.authors.map((link) => link.author.id),
      ...page,
    },
  });
});
```

Passing `authorIds` into the context makes it available for the query in `BlogPage.tsx` and means we can pull only the authors we need for that page.

After that, it is just a matter of passing the authors down into the right component to display them, without relying on `.document` links and having full TypeScript support.

**Comment by kb1995** [comment]
@angeloashmore Just pinging you in case you missed it

**Comment by kb1995** [comment]
@angeloashmore Sorry to be bothering you, but I'm still experiencing the Proxy issue one year later...

**Comment by angeloashmore** [comment]
Hey @kb1995, so sorry for the lack of replies here! It definitely wasn't intentional.

The use of a proxy shouldn't be causing an issue in this case. All properties pass through to the API's original value except `document`, which connects the Content Relationship field's document to the document's data.

That's not to say there isn't an issue, but the proxy shouldn't be the reason.

> isFilled.contentRelationship(authors[0])) is true when not in preview
> isFilled.contentRelationship(authors[0])) is false when in preview

`isFilled` is designed for Prismic's REST API which always includes all of a field's properties. In Gatsby, fields usually do not always contain all properties since you can use GraphQL to selectively choose your data.

For `isFilled.contentRelationship()` to work in Gatsby, the field must include at least one of the following fields: `id`, `url`

You can see how the function is implemented here: https://github.com/prismicio/prismic-helpers/blob/95bdc898061ec89d8789fe32ea8f95500f6e9359/src/isFilled.ts#L123

In the case where at least `id` or `url` is not queried, the results should be opposite of what you posted; it should be `false` when not previewing and `true` when previewing. During previews, all fields are automatically included.

---

If the above doesn't help fix the issue, could you share a reproduction project that shows this issue? I can help debug and fix the issue, but I'm not seeing the issue on my side unfortunately.
