### ISSUE TITLE
How do you develop this plugin locally?

### ISSUE THREAD

**Issue by veloce** [prismicio/prismic-gatsby#242]
Hi @angeloashmore this is more a question than an issue. But I have trouble when installing this plugin locally to work on it. Since I'm new to gatsby I probably miss the best practices for developing a plugin.  

Here is what I do to setup a dev env:
- I have a sample project to test the plugin against
- I install the plugin using `npm install ../path/to/plugin` (I found no difference in doing that rather than using the `plugins` folder)
- to avoid a build time error caused by a mismatch of graphql modules, I make sure that only the graphql module from the plugin is used: `rm -r node_modules/graphql && ln -s /path/to/plugin/node_modules/graphql node_modules/graphql`
- now I'm stuck with this error:
```
Generating development JavaScript bundle failed


~/dev/gatsby-source-prismic/dist/gatsby-browser.js
  1:205  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
```

I find it weird that gatsby doesn't like the dist file of the local plugin when it is working fine when the  plugin is pulled from npm. I don't know if the last error is coming from my setup or not. I'm more asking for general good practices when developing a plugin (I could find much on internet about this) to avoid those errors that I'm usually seeing.

Thanks!

**Comment by angeloashmore** [comment]
Hi @veloce,

There are two methods I use. Note that I use Yarn 1 rather than `npm` which may act differently.

**Test-based**
If you are working on a smaller feature that can be handled just by checking that existing tests pass, there shouldn't be a need to perform any special setup.

1. `yarn install`
2. Make changes and update/add tests if needed
3. `yarn test`

**Workspace-based**
If you are working on a larger feature or a feature that requires working against a live development server, Yarn Workspaces is the easiest method. I'm not sure if there's an NPM equivalent.

1. Create a directory with the following structure:
   - `/packages/`
      - `/packages/gatsby-source-prismic`
      - `/packages/your-test-gatsby-site`
   - `/package.json` (this root-level package.json just sets up the Workspace)
      ```json
      {
        "version": "0.0.0",
        "private": true,
        "workspaces": {
          "packages": [
            "packages/*"
          ],
          "nohoist": [
            "**/husky",
            "**/husky/**"
          ]
        }
      }
      ```
2. `yarn install` somewhere in the workspace
3. In `gatsby-source-prismic` or the Gatsby project, you can run Yarn commands like normal. Node dependencies will be shared in the root `node_modules` folder.

You should be able to achieve a similar setup without Workspaces by linking `gatsby` and `react` from the Gatsby project into the `gatsby-source-prismic` directory.

That error looks like something from ESLint which shouldn't be checked during `gatsby develop`.

Let me know if you're having trouble with the setup. I'll admit that I haven't used NPM since Yarn 1 came out, but I find it to be a much simpler tool to use, especially when working with inter-dependant projects.

**Comment by veloce** [comment]
Thanks for your detailed answer @angeloashmore . I'll try that.

**Comment by MarcMcIntosh** [comment]
Hi @angeloashmore 

Thanks for the advice, yarn workspaces looks like a handy feature. 

We still had the error and managed to solve it with
`echo "../gatsby-source-prismic/dist/*" >> packages/gatsby-starter-default/.eslintignore`

**Comment by angeloashmore** [comment]
@MarcMcIntosh I typically have a custom ESLint config in my projects so that may be why I don't see that. Does your test site use one, or is it just the Gatsby defaults?

**Comment by veloce** [comment]
Just the Gatsby defaults. We could fix the issue by adding the `dist/` folder to eslintignore.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. The latest versions of the plugin use a different architecture that should work as expected.
