### ISSUE TITLE
Graphql Filtering Not Working as Expected

### ISSUE THREAD

**Issue by twslade** [prismicio/prismic-gatsby#254]
Thanks for the great tool! As part of our v3 migration, I've decided to leave in Placeholder content until we successfully deploy v3. The placeholder content is identified with tags i.e. "Placeholder" tag.

I'm trying to filter using tags with a `ne` condition like so which isn't working for tags. There is an object that contains a "Placeholder" tag, but its as if it is getting ignored when trying to exclude it.

**Dependencies**
"gatsby": "^2.24.0",
"gatsby-source-prismic": "^3.2.1",

### Filtering With Single Object Query
Query:
```graphql
{
  prismicSitewide(tags: {ne: "Placeholder"}) {
    tags
  }
}
```

Result:
```json
{
  "data": {
    "prismicSitewide": null
  },
  "extensions": {}
}
```

---

### Filtering all Objects

Query:
```graphql
{
  allPrismicSitewide(filter: {tags: {ne: "Placeholder"}}) {
    nodes {
      tags
    }
  }
}
```

Result:
```json
{
  "data": {
    "allPrismicSitewide": {
      "nodes": []
    }
  },
  "extensions": {}
}
```
---

### List of all Objects without filtering (includes placeholder tag)
Query:
```graphql
{
  allPrismicSitewide {
    nodes {
      tags
      data {
        newsletter_signup_text
      }
    }
  }
}

```
Result:
```json
{
  "data": {
    "allPrismicSitewide": {
      "nodes": [
        {
          "tags": []
        },
        {
          "tags": [
            "Placeholder"
          ]
        }
      ]
    }
  },
  "extensions": {}
}
```

All of these tests were run after a single instance.

**Comment by angeloashmore** [comment]
Hi @twslade, sorry for the late response. I'm seeing the same thing here.

It's worth noting that `eq` and `in` work as expected (not that it solves what you need to do).

It seems related to the fact that when using the other comparators, such as `ne`, `nin` or regex, nodes with empty arrays are excluded from the result. Since your list of nodes only contains one node with tags (the one with "Placeholder"), and your filter removes that node using `ne`, you are left with no results.

I'm not sure if this is a bug with Gatsby's ["fast filtering"](https://www.gatsbyjs.com/docs/query-filters/#history-and-sift) system or if this is the intended result. The underlying data for each Prismic node is just an array of strings (e.g. `[]` or `["Placeholder"]`), and is represented correctly in the GraphQL types. It's possible that this is the intended result since there isn't a way to filter out nodes with empty arrays (i.e. there isn't an option in `filter` to say "filter out nodes where `tags` is empty").

Would you mind opening an issue in the Gatsby repo to see if this is something on Gatsby's end?
