### ISSUE TITLE
Saving in Prismic reloads page, drops out of preview mode

### ISSUE THREAD

**Issue by patspam** [prismicio/prismic-gatsby#261]
Thanks for creating an awesome plugin.

I've got preview mode working using `withPreview` and `withPreviewResolver` - I click the PREVIEW button in Prismic, which takes me to `/preview` on my dev site, which then correctly navigates me to the correct page url and I see preview content. So far so good!

However, when I make a new edit and save in Prismic (in a separate tab), my site reloads and I'm dropped out of preview mode. I then have to use the toolbar or Prismic site to enter preview mode again.

What's supposed to happen when a remote edit happens? I'm tantalisingly close to live editing. Any tips on debugging what's going wrong here?

**Comment by angeloashmore** [comment]
To be honest, I didn't know this was a feature of Prismic! The current preview system only populates/fetches preview documents when landing on the /preview page with the correct URL parameters. Since the page refreshes on the document's page rather than the preview resolver page, it doesn't fetch the preview.

To support this, we could instead check for the presence of a cookie that persists between page refreshes. Doing something like that is probably more inline with how Prismic expects developers to implement previews.

For now, live previews is unsupported. Implementing this behavior should be a matter of changing `withPreview` to detect that cookie and perform something similar to what `withPreviewResolver` is doing now.

**Comment by mylo** [comment]
Any updates on live previews @angeloashmore  ?

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. The new preview plugin, `gatsby-plugin-prismic-previews` supports this now!

You can learn more here: https://prismic.io/docs/technologies/previews-gatsby
