### ISSUE TITLE
AccessToken exposed in browser

### ISSUE THREAD

**Issue by patspam** [prismicio/prismic-gatsby#264]
This plugin currently exposes the `accessToken` in the browser via `window.__GATSBY_SOURCE_PRISMIC__.REPO.pluginOptions.accessToken`.

This isn't good if you have a private Prismic repo, as anyone who knows the `accessToken` can query your data using the Prismic API.

Perhaps there should be an option to only include the `accessToken` when the Prismic toolbar (preview mode) is being used. Or better yet, find another mechanism so that it can stay out of compiled code entirely. With the current behaviour, there should probably be a big warning in the README.md so that people with private repos don't get a nasty surprise (I was expecting it to only be used at Gatsby build time).

I pinged @angeloashmore off-list before posting this (since it's security related), these are his comments for reference:

> You're right - as long as the preview token provided by Prismic allows querying for documents freely for that release (which I believe it does), then there isn't a need to store the access token in that window object
> The presence of a gatsby-browser API automatically exposes all plugin options (at least it did in previous versions of Gatsby, haven't tested it in a while)
> If you don't mind, could you post an issue for this on the repo? I appreciate reaching out before making it public. In this case, it would be helpful to get others' thoughts and potentially a PR to modify the current access token behavior

**Comment by patspam** [comment]
FYI: My temporary fix is a `postbuild` script in `package.json` that uses grep/sed to replace all instances of the `accessToken` in Gatsby compiled code with a dummy string.

eg. In `package.json`:
```json
"scripts": {
  "postbuild": "for i in $(grep -Rl $key public); do sed -i '' -e \"s/$key/REVOKED/g\" $i; done"
}
```

**Comment by angeloashmore** [comment]
@patspam Spent some time thinking about this and hoping to get some feedback.

## Problem

As you mention, the Prismic access token is made public in `window.__GATSBY_SOURCE_PRISMIC__.REPO.pluginOptions.accessToken`. This should be removable since the access token's use in `usePrismicPreview` can be replaced by the new token provided when triggering a preview.

This does not solve the problem completely, however. Although we can remove the access token from appearing in that window property, all plugin options, including secrets and your JSON schemas, are saved in your site's `app-XXX.js` file, where `XXX` is a hash.

When any Gatsby plugin includes a `gatsby-browser.js` file with at least one API implemented (this plugin uses `onClientEntry`), all of its plugin options are included in the site's `app.js` bundle. This is necessary since those APIs may need access to arbitrary plugin options. In our case, we need access to things like `fetchLinks` and `prismicToolbar` to setup previews correctly in the browser. So even though we don't need `accessToken`, the other pieces of data we do need forces the token to be injected.

For example, this is `gatsby-source-prismic`'s `gatsby-browser.ts` file. This function is run in the browser, so in order for the Gatsby runtime to provide `pluginOptions` as the second argument, it must save all the plugin options in the built, public version of the site.

```typescript
// gatsby-browser.js

export const onClientEntry: GatsbyBrowser['onClientEntry'] = (
  _gatsbyContext,
  pluginOptions: BrowserPluginOptions,
) => {
  if (pluginOptions.prismicToolbar === 'legacy')
    // The legacy Prismic Toolbar script requires setting the endpoint globally
    // to window.
    window.prismic = {
      endpoint: `https://${pluginOptions.repositoryName}.cdn.prismic.io/api/v2`,
    }

  window[BROWSER_STORE_KEY] = Object.assign({}, window[BROWSER_STORE_KEY], {
    [pluginOptions.repositoryName]: {
      pluginOptions: omit(pluginOptions, ['schemas', 'plugins']),
      schemasDigest: md5(JSON.stringify(pluginOptions.schemas)),
    },
  })
}
```

## Possible Solutions

1. **Recommend users setup a postbuild script to redact the access token**

Your solution is an elegant patch. This is not a great long-term solution, IMO, as it doesn't solve the root issue. It is, however, a good temporary fix for now.

2. **Separate the data sourcing from previewing**

Gatsby source plugins are intended to do one thing: source data and add save it to Gatsby's store. Anything past that, including page creation and browser enhancements, is not within the domain of a source plugin. `gatsby-source-prismic` has been lax around that rule and implements browser APIs as a convenience. This ultimately is the reason the access token is exposed.

To better align with Gatsby's framework and eliminate the exposure of secrets in the browser, a separate plugin could be made available. By separating the source plugin from the preview plugin, we can isolate the access token to just the source plugin. It could look something like this:

```javascript
{
  plugins: [
    {
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: process.env.PRISMIC_REPOSITORY_NAME,
        accessToken: process.env.PRISMIC_ACCESS_TOKEN,
        schemas: require('./src/schemas'),
        fetchLinks: ['data.parent'],
        // etc...
      }
    },
    {
      resolve: 'gatsby-prismic-previews',
      options: {
        repositoryName: process.env.PRISMIC_REPOSITORY_NAME,
        // etc...
      }
    }
  ]
}
```

This would allow explicit opt-in behavior for previews. It also opens the door to any other kinds of non-source-plugin functionality we want without feeling guilty. Note that `gatsby-prismic-previews` would not include the access token and requires duplicating some options like `fetchLinks`.

This would take some extra work to make, of course, and is a breaking change for those who have already implemented previews. The upgrade path should be simple, however.

---

Any thoughts on these approaches? I'm open to anyone's opinion on how we can best approach this.

**Comment by patspam** [comment]
Thanks Angelo.

I guess the other way to do it would be with an environment variable, but I much prefer the split plugin approach.

**Comment by angeloashmore** [comment]
Upon further reading, it appears this is not something Prismic supports. If your repository is private, **all** API calls require the access token, including previews. The token provided by the preview request from the Prismic API is not an access token, but rather a ref to the preview state.

It would be nice if Prismic had a way to detect your `https://prismic.io` logged-in state to authenticate preview requests.

See https://github.com/birkir/gatsby-source-prismic-graphql/issues/45 for a similar discussion in the GraphQL source plugin.

Still, separating preview functionality allows for better separation of concerns and clearer opt-in behavior. It will *not* hide the access token automatically, however.

A recommended approach could be setting up two instances of your site, which could be controlled via an ENV var:
1. With the preview plugin enabled behind some kind of auth (e.g. HTTP basic auth). The access token will be in the bundle.
2. Without the preview plugin. No access token in the bundle.

**Comment by patspam** [comment]
I agree that would work, but it's a bit of a sledge-hammer approach. Adding HTTP basic auth is not always simple - for example if you're deployed to AWS S3/CloudFront then you need to write custom Lambda@EDGE functions to do it.

How about if the plugin had an option to read the access token from a cookie? You could even provide convenience methods for setting/clearing the cookie, prompting the user for the key, etc.

**Comment by angeloashmore** [comment]
That's a great idea. So someone could provide an access token as a plugin option and it's always available (and public). Otherwise, if a token isn't provided, the editor will be prompted for the access token on the first preview and gets saved to a cookie. This seems like the cleanest way to handle access tokens.

Good point about auth not always being simple.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. This strategy was implemented in `gatsby-plugin-prismic-previews` ([details here](https://labs.walltowall.com/gatsby-source-prismic-v4-roadmap/#private-plugin-options)).

Thanks again @patspam for the idea!
