### ISSUE TITLE
Previewing linked content entities

### ISSUE THREAD

**Issue by antoinegrelard** [prismicio/prismic-gatsby#273]
Hi ! I'm wondering if there's a proper / different way to preview linked content updates.

Here's a screenshot from my homepage : 
<img width="1274" alt="Capture d’écran 2020-09-30 à 17 11 05" src="https://user-images.githubusercontent.com/6814745/94704847-a5d63000-0340-11eb-866e-4a24267d40c0.png">

If I update the carousel title field, save and preview, I can see the text updated correctly.

If I update one of the cards, they are a separate content type and currently the only way for me to preview the update on one of this cards is to publish the card, and preview the homepage content type directly.

I was wondering if there was a way of simple updating the card content type entity, save, and preview directly from it ?

I understand from the limitations here : https://github.com/angeloashmore/gatsby-source-prismic/blob/master/docs/previews-manual-setup.md#limitations that my request might fall into this use-case : "https://github.com/angeloashmore/gatsby-source-prismic/blob/master/docs/previews-manual-setup.md#limitations"

Let me know if there's anything I can do to avoid publishing the cards entity or if that's the only way to preview them.

Thanks !

**Comment by angeloashmore** [comment]
Unfortunately, yes, your case falls into the current limitations of the preview system.

For large website changes (i.e. not a one-off preview/change), you can setup a Release in Prismic and build a separate staging site from that release. Using that method, you wouldn't be publishing changes to you live site, but you could still view your whole site with the changes. This of course will be slower than clicking the Preview button since you will need to rebuild your site using that specific Release ID, but it could be a viable solution for larger, site-wide changes.

I do have ideas of how to overcome this limitation, but it is current unsupported.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. The new preview plugin, `gatsby-plugin-prismic-previews`, fully supports Releases. This allows you to preview multiple documents edits at once before publishing.
