### ISSUE TITLE
A few questions about getting previews working for templates

### ISSUE THREAD

**Issue by alexolotl** [prismicio/prismic-gatsby#277]
I'm trying to get previews working for unpublished generated template pages, but stumbling on a few points.  I'm using withUnpublishedPreview() in my 404 component with the correct templateMap for my template Project component specified, but when previewing in Prismic it says there is not a page yet at that path.

There are a few points that are unclear to me about setting up previews, so not sure if any of them are the cause.

First, when using withUnpublishedPreview(), am I supposed to add a setting to provide it the {context: uid: doc.uid} needed to populate the query on the generated template page, as I do when calling createPage() in gatsby-node?

I'm not sure this is the cleanest way to handle linkResolver, but in mine I added manual routes for my Gatsby src/pages page urls based on Prismic doc.type (these are non-repeating document types). I don't provide uid's to these in Prismic, since Gatsby seems to generate their urls based on src/pages filename. I provide uid's to my repeating (project) types in Prismic, and am generating pages based on that. Is this structure of linkResolver possibly the reason for my unpublished templates not to work?

```
linkResolver: ({ node, key, link }) => (doc) => {

  if (doc.type === `homepage`) return `/`

  if (doc.type === `about_page`) return `/about`

  if (doc.type === `project`) {
    if (doc.uid) return `/projects/${doc.uid}`
    return `/projects`
  }

  return `/`
}
```

Am I supposed to be able to navigate around the site in my preview from Prismic, or just to see one page per preview based on linkResolver? (For example, I have both a "projects" navigation page, and individual "project" template pages, and would be useful to see both from a project preview - or to see the full site after clicking Preview on my site theming Prismic document)

I'm a bit confused about the status of needing to add "prismicId" into queries for previews, is this required?

Also, one last part I'm unsure of- in Prismic in the settings for my repo, I added a Preview endpoint. Since I'm testing locally I set the domain to http://localhost:8000, and set the "Link Resolve" input to "/preview". For gatsby-source-prismic previews, is this correct? It seems to work fine when I click the eye icon on Prismic for most pages (other than unpublished templates) - but I'm not sure where this "/preview" comes in, or if I should include it in my linkResolver or anywhere in my site code.

Thanks so much for the help

**Comment by rootion** [comment]
I managed to get previews working with unpublished pages after struggling with the documentation, so maybe I can help you. But your issue is too long, there is too much text and too many points to address. 

1) Did you add your link resolver to gatsby-config?
2) The `preview` endpoint is an example word. If you add that word to the preview setting in prismic, you need to create a page in gatsby called `preview.js`. That page needs to follow [this example](https://github.com/angeloashmore/gatsby-source-prismic/blob/master/docs/previews.md#withpreviewresolver) and also add in there your link resolver.
3) Then you also need to add a 404.js exactly as explained in that documentation.

If you did these things and still have issues, let me know which specific issue you have and I see if I can help you.

**Comment by angeloashmore** [comment]
Hi @alexolotl,

> First, when using withUnpublishedPreview(), am I supposed to add a setting to provide it the {context: uid: doc.uid} needed to populate the query on the generated template page, as I do when calling createPage() in gatsby-node?

Unpublished previews don't have a way of providing values to `pageContext` like pages made in `gatsby-node.js`. This is because unpublished previews are only rendered client-side. You can think of it as just rendering a normal React component with the preview data provided on the `data` prop.

Limiting use of `pageContext` is recommended. If you can reduce `pageContext` to just the document's ID, you can query everything else using the page/template's GraphQL query. Then it theoretically work in an unpublished preview since your document data would come only from the `data` prop.

> I'm not sure this is the cleanest way to handle linkResolver, but in mine I added manual routes for my Gatsby src/pages page urls based on Prismic doc.type (these are non-repeating document types).

Your link resolve looks correct to me 👍. It shouldn't be the reason for broken previews. If you are creating pages in `src/pages` that query for specific documents, then your setup is correct. The preview resolver page (usually `/preview`, which I'll discuss in your last question) will use the link resolver to determine which page to redirect the browser.

The link resolver is also used to generate URLs whenever you relate documents with each other. If you had a link in a Rich Text field to your About page, for example, the link resolver would need to know how to convert the document into `/about`.

> Am I supposed to be able to navigate around the site in my preview from Prismic, or just to see one page per preview based on linkResolver?

This is a limitation of the preview system currently. It will store which URL should contain preview data (computed using the link resolver) and will only make the preview data available on that page. With the introduction of the `_previewable` field (previously `prismicId`), we can possibly make it available everywhere with some work.

> I'm a bit confused about the status of needing to add "prismicId" into queries for previews, is this required?

Yes, it is required, but use the `_previewable` field instead. `prismicId` was the previous field we used but the API felt arbitrary. The plugin will still work if you do not include it, but that will chance on the next major version. Sorry, this is not documented yet but you will see a message in your console if you are missing the `_previewable` field.

>Since I'm testing locally I set the domain to http://localhost:8000, and set the "Link Resolve" input to "/preview". For gatsby-source-prismic previews, is this correct?

This is correct. You can create more than one preview endpoint in Prismic. I usually have one for Development (`http://localhost:8000/preview`) and one for Production (`https://example.com/preview`). The `/preview` endpoint comes from needing to create a page at `src/pages/preview.js` that includes `withPreviewResolver` ([see the docs here](https://github.com/angeloashmore/gatsby-source-prismic/blob/86f391ecbcc699b8872b954306608ef3bc2fdd06/docs/previews.md#withpreviewresolver)).

Could you go over the whole Previews documentation and double check that everything is configured correctly? An important part to check for is the inclusion of `linkResolver` when using `withPreviewResolver`.

---

Thank you @rootion for providing those answers as well. Your example repo is a good reference for the minimal setup required.

**Comment by alexolotl** [comment]
Thank you @angeloashmore and @rootion for your answers and the example repo, the clarifications are helpful and I got everything running now.

I made some adjustments, and it turned out I made a pretty obvious mistake - I was using a Gatsby starter and didn't realize Gatsby's development 404 page has a link within it to be redirected to the app's actual 404 component page (and therefore redirected to the unpublished preview page). At first I saw the development 404 and thought it was a dead end.

Thanks!

**Comment by Jrousell** [comment]
Hi @alexolotl, did you manage to get unpublished previews to "bypass" the dev 404 page? In my setup all unpublished previews land on the dev 404 page but can be accessed by clicking the show custom 404 link. Published previews work fine, just can't seem to get unpublished ones working. Thanks.

**Comment by NeversSync** [comment]
@Jrousell I'm having the same issue. Unpublished previews are landing me on the gatsby 404 page, I'd expect to be directed past that intermediary stage but I can't find a way to make that happen.

**Comment by angeloashmore** [comment]
@Jrousell @NeversSync You could try adding this to your `gatsby-node.js` file:

```js
exports.onCreatePage = ({ page, actions }) => {
  if (process.env.NODE_ENV !== `production` && page.path === `/404/`) {
    const { createPage } = actions
    // Make the 404 page match everything client side.
    // This will be used as fallback if more specific pages are not found
    page.matchPath = `/*`
    createPage(page)
  }
}
```

Taken from https://github.com/gatsbyjs/gatsby/issues/16112#issuecomment-515432302

This should make your 404 page take priority over the development 404 page. Let me know if this works!

It's worth noting that the development 404 page is expected to show normally. We are relying on the 404 page to handle any unpublished previews since that will be the page editors will land on for pages that don't yet exist. In production, users will not see the Gatsby development 404 page with the extra button click to see your preview.

**Comment by NeversSync** [comment]
@angeloashmore Got it, thank you! 
I'm just going to leave the development 404 as is, not a big deal after some more consideration.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!
