### ISSUE TITLE
Question: How best to handle lang/alternative_languages

### ISSUE THREAD

**Issue by jodiedoubleday** [prismicio/prismic-gatsby#291]
I have a component Header which uses a static query to bring back data from a navigation single type document from Prismic.

I want to start using the multilingual capabilities of Prismic so I just wanted to ask if anyone has any suggestions on the best way to do this?

Using a static query on allPrismicNavigation will bring back the first navigation language it finds, and you can't (as far as I'm aware) pass through a lang variable into the query (or maybe you can with pageContext?). So in this instance even if I'm on a **fr-fr** page the navigation is always **en-gb**

The only way I can think of this working is by querying the navigation data on the template query then passing the results of that query to the header component, this will make sure that whatever language the page is in, the navigation follows suit. 

It seems a bit convoluted. 
*any help much appreciated**

**Comment by Floriferous** [comment]
Agreed, I haven't found a great pattern here either.

I can only think of 2 solutions right now:
* Query `allPrismicNavigation` in all languages, and then filter the results of that query in your component based on the language your currently in. This means you're fetching unnecessary data in multiple languages.
* Create a per-language querying component that only fetches the data for one language and wraps your UI component
  * Unmanageable if your site works in a lot of languages, or if people can easily add new languages as it'll break

**Comment by angeloashmore** [comment]
Hey, sorry I didn't get a chance to reply here. I'm cleaning out old issues and closing this due to its age.

As far as handling multiple languages with static queries, the only way to do this is to query all languages and find/filter the correct one in JavaScript at runtime.

If you add the query to your pages, however, you have access to page context via variables. You should be able to set a `$lang` variable when generating your pages which can be used in your query.
