### ISSUE TITLE
Hard to debug error: `Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not`

### ISSUE THREAD

**Issue by madeleineostoja** [prismicio/prismic-gatsby#329]
Sorry if this isn't the place for this, but my Prismic source is throwing a GraphQL validation error, and the whole stacktrace doesn't mention where it's coming from. Any ideas what this could mean, and where I'm going wrong?

It's just this error repeated over and over again (I'm guessing for every node), during dev or build:

```
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
```

**Comment by angeloashmore** [comment]
Hey @madeleineostoja, check out this issue: https://github.com/angeloashmore/gatsby-source-prismic/issues/249#issuecomment-777899973

I haven't looked into how the labels field from the schema leaks into the GraphQL side of things, but most likely that's what your error is.

**Comment by madeleineostoja** [comment]
Yep that was it! I was pulling my hair out trying to figure out where it was coming from, and I don't now how I missed that issue. 

If Prismic often misbehaves in this way might be worth noting in the readme?

**Comment by angeloashmore** [comment]
Yes, definitely. I’ll leave this issue open as a reminder to document or hopefully eliminate in V4.

**Comment by angeloashmore** [comment]
Just had a thought: I believe this happens because the `schemas` plugin option directly includes the JSON objects. These are added to Gatsby's GraphQL store since all plugins and their options are queryable via GraphQL. So the Prismic source plugin isn't adding any fields with an empty name directly, but it happens implicitly since all plugin options become queryable.

I don't have a solution to this yet, just figured I'd document it here.

Providing the file path to the schemas and reading the files directly may *not* be a viable solution since we will eventually have a way to fetch schemas automatically from the Prismic API. The easiest implementation for that system was to assign the fetched schemas as a default plugin value, but that means the same issue will occur.

**Comment by angeloashmore** [comment]
This issue is stale and may be fixed in a recent version. Please update to the latest version and try again. If the issue continues to be a problem, please open a new issue. Thank you!

See the documentation for guides on updating to the latest versions: [Gatsby + Prismic Migration Guides](https://github.com/prismicio/prismic-gatsby/tree/main/docs#migration-guides)
