### ISSUE TITLE
w(...) is not a function

### ISSUE THREAD

**Issue by NLeRoy917** [prismicio/prismic-gatsby#331]
Hello! Just set up a personal site/blog using prismic and gatsby - love it so far. Although, I can't get previews to work. If I save a document, add it to a release, then attempt to view its preview, gatsby throws an error: 

`w(...) is not a function`

It looks like it comes from here:
**`./node_modules/gatsby-source-prismic/dist/gatsby-source-prismic.modern.js:180`** and it points at this code:
```js
  178 |       hydratedOptions.pathResolver ?? hydratedOptions.linkResolver
  179 |     const path = resolvedPathResolver
> 180 |       ? resolvedPathResolver({ node: doc })(doc)
      |                                            ^
  181 |       : undefined
  182 | 
  183 |     dispatch({ type: ActionType.DOCUMENT_LOADED, payload:
```

I'm not too sure how to address this since it seems to be related to the `gatsby-source-prismic` package itself. Here is a screenshot:

![image](https://user-images.githubusercontent.com/41063083/113366737-111cb100-9328-11eb-86d3-23cd5ab30363.png)

**Comment by angeloashmore** [comment]
Hey @NLeRoy917, sorry you didn't get a reply here. I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!

FYI this error probably appeared because the plugin did not receive a Link Resolver function. The latest version of `gatsby-plugin-prismic-previews` was a rewrite of the preview functionality that should work better now.
