### ISSUE TITLE
Failing processing image - V4 

### ISSUE THREAD

**Issue by newadbie** [prismicio/prismic-gatsby#389]
Hey, i have a issue with v4 gatsby-source-prismic. When i input "gatsby develop" or "gatsby build" i see this error 
`Unexpected error value: "failed to process
https://images.prismic.io/my-reponame/db9757c5-4ce1-46e9-8834-ead4d9cbbca8_default_a1f5f3dfbc.png?auto=compress,format\nRequestError: connect   
ETIMEDOUT xxx.xxx.xx.xxx:443"`.
I know it is coming from beta version because when i use my current version which work with v3 prismic, everything work correctly, the error only shows while using v4 version. 

Best Regards! Zilib

**Comment by angeloashmore** [comment]
Hey @newadbie / Zilib,

This error displays when `gatsby-source-filesystem` cannot download the file in time. There are many reasons this could happen (Imgix timing out, local network issues, etc.). Note that using the Imgix fields (i.e. not `localFile`) will prevent this issue.

One solution may be to reduce the number of concurrent downloads `gatsby-source-filesystem` is performing. By default, it downloads up to 200 files at once.

Could you try setting this environment variable when running `gatsby develop` or `gatsby build` and let me know if it works?

```
GATSBY_CONCURRENT_DOWNLOAD=1 gatsby develop

# or

GATSBY_CONCURRENT_DOWNLOAD=1 gatsby build
```

This will increase the download time as it will only download one image at a time. You can adjust this number higher if you find it works for you.

**Comment by jodiedoubleday** [comment]
I'm also getting image issues locally, but the URLs from graphwl don't seem correct...
`https://images.prismic.io/juniper-studio/992354f7-58ef-4c4a-962f-494df444c922_mockup-braun.jpg%3Fauto=compress%252Cformat?ixlib=gatsbyFP&auto=compress%2Cformat&fit=max&q=50&w=116&h=77`

removing the `%3Fauto=compress%252Cformat` before the `?` seems to fix it.

**Comment by angeloashmore** [comment]
Hey @jodiedoubleday, can you update to the latest `gatsby-source-prismic` and `gatsby-plugin-prismic-previews` and let me know if that's fixed?

Imgix pushed out an update to their Gatsby plugin which changed the way it processed URLs so I had to change some of the logic here.

**Comment by jodiedoubleday** [comment]
@angeloashmore works a treat ✅

**Comment by rafalohn** [comment]
I'm also getting issues with `localFile{ChildImageSharp{gatsbyImageData}}}` with V4:

>  "Unexpected error value: \"failed to process https://images.prismic.io/testelohn/cc1e4a16-7b2e-47ff-aac8-c135904ec0f3_testeheader2.png?auto=compress,format\\nFailed to download https://images.prismic.io/testelohn/cc1e4a16-7b2e-47ff-aac8-c135904ec0f3_testeheader2.png?auto=compress,format after 3 attempts\"" 

This happens with all my localFile gatsbyImage queries. Although all the error message URLs - such as the above - work fine and I had no issues with `gatsby-prismic-source` V3. 

Currently trying to upgrade to V4 with the following:
> 
    "gatsby": "^3.10.2",
    "gatsby-plugin-image": "^1.10.1",
    "gatsby-plugin-prismic-previews": "^4.0.3",
    "gatsby-plugin-sharp": "^3.10.2",
    "gatsby-source-filesystem": "^3.10.0",
    "gatsby-source-prismic": "^4.0.2",
    "gatsby-transformer-sharp": "^3.10.0",

**Comment by rafalohn** [comment]
As a follow-up, I could swear I made it work _once_ when I updated to `" gatsby": "^3.11.0",`. But it stopped working and I am back to the same error.  I am using macOS Big Sur and my colleague with the same OS has the same error. But my colleague using Linux can run this exact branch with no errors whatsoever! We are all using Node v16.6.0.
I did try `GATSBY_CONCURRENT_DOWNLOAD=1 gatsby develop`. with no success.

**Comment by rafalohn** [comment]
Workaround found! Turns out that if we use `npm` instead of `yarn` it works as expected.

**Comment by angeloashmore** [comment]
That's strange! I'm glad you found a workaround!

For context, the error comes from `gatsby-source-filesystem`, not `gatsby-source-prismic`. It is, however, a result of using the `localFile` field within a Prismic document's Image or Link to Media field.

Are you able to open an issue in the [Gatsby repository](https://github.com/gatsbyjs/gatsby) for `gatsby-source-filesystem`? I'm not familiar enough with the internal workings of `gatsby-source-filesystem` to debug the issue.

**Comment by rafalohn** [comment]
I'll look into it. But, meanwhile, I see that @jodiedoubleday used to have issues with the image path ending in (for example) `?auto=compress,format`. How can I force remove it from the URL to see if it fixes the issue? Maybe it helps...

**Comment by angeloashmore** [comment]
@rafalohn You can customize the Imgix URL parameters using the `imageImgixParams` plugin option.

**See**: https://prismic.io/docs/technologies/install-the-plugin-gatsby#3.-configure-the-plugin

> **options.imageImgixParams**: Provide a default set of [Imgix image transformations](https://docs.imgix.com/apis/url) to your images. These options will override the default [Imgix transformations set by Prismic](https://user-guides.prismic.io/en/articles/3309829-image-optimization-imgix-integration).

If you are downloading the images locally with the `localFile` field, then removing `auto=compress,format` is okay. `gatsby-transformer-sharp` will compress them instead.

If you are using Imgix URLs with `gatsby-plugin-image`, removing `auto=compress,format` is not recommended since images will not be properly optimized.

It sounds like you're using `localFile` so you can set `imageImgixParams` to `{}` to remove all default Imgix URL parameters.

**Comment by rafalohn** [comment]
Adding `imageImgixParams: {}` did not remove the parameters from the URL path. I still got the same

>Error: Unexpected error value: "failed to process https://images.prismic.io/testelohn/cc1e4a16-7b2e-47ff-aac8-c135904ec0f3_testeheader2.png?auto=compress,format\nFailed to download https://images.prismic.io/testelohn/cc1e4a16-7b2e-47ff-aac8-c135904ec0f3_testeheader2.png?auto=compress,format after 3 attempts"

To be clear, I have components such as
```
import { GatsbyImage, getImage } from "gatsby-plugin-image"
(...)
<GatsbyImage image={getImage(image.localFile)} />
```
using something like
```
import { graphql, useStaticQuery } from "gatsby"
(...)
graphql`
(...)
localFile {
  childImageSharp {
        gatsbyImageData(
          layout: FULL_WIDTH
          placeholder: BLURRED
        )
      }
    }
(...)
```
This works in `gatsby-source-prismic` V3 and now works in V4 with `npm`. But with `yarn` I got the error above.

**Comment by angeloashmore** [comment]
@rafalohn I might have misremembered. Can you try `imageImgixParams: { auto: undefined }`? Or set auto to an empty string?

The params are basically is spread over the existing params.

**Comment by rafalohn** [comment]
Both `imageImgixParams: { auto: undefined } ` and `imageImgixParams: { auto: "" } `  kept `?auto=compress,format` on my image URLs.

**Comment by angeloashmore** [comment]
Thinking more about this, that makes sense. The `imageImgixParams` option only applies to the Imgix fields (`fluid`, `fixed`, and `gatsbyImageData`). Note that these are the image-level fields, not the fields within `localFile.childImageSharp`.

The `localFile` field downloads the original URL given directly from Prismic.

**Should the `localFile` field apply the provided `imageImgixParams` to the locally downloaded file?** Since `localFile` can also contain non-image files (think: a Link to Media field linked to a PDF), it would only apply to image URLs.

**Comment by rafalohn** [comment]
I guess `imageImgixParams` should be ignored if I am aiming for local `gatsbyImageData`.

I can't help the feeling that there is some sub-dependency somewhere that `npm` install differently than `yarn` and that's why one works and the other doesn't. And, since I have this problem with `gatsby-source-prismic` V4 but not V3, it probably is some new dependency or a newer version of a previously used one. Does that make sense? Any possible suspects?

**Comment by rafalohn** [comment]
Happy to share that today I updated to `"gatsby": "^3.12.0",` (and likewise to the `#.12.0` for the `gatsby-plugin-##` family) and now I can use `yarn` and no longer have the
> Error: Unexpected error value: "failed to process URL...

errors I had before. Looks like it is working as expected for me and my colleagues. Thank you for your support and great work @angeloashmore

**Comment by angeloashmore** [comment]
That's great to hear! Sorry I wasn't able to provide more support here. I'm still not sure what the underlying issue is causing that error.

I'm going to close this issue as it sounds like using the latest version of Gatsby and its plugins will fix the issue. If it comes back, we can reopen and investigate. Thanks!
