### ISSUE TITLE
[v4] Shareable links not working

### ISSUE THREAD

**Issue by jordyvg** [prismicio/prismic-gatsby#403]
I've followed the [gatsby-plugin-prismic-previews instructions](https://github.com/angeloashmore/gatsby-source-prismic/tree/alpha/packages/gatsby-plugin-prismic-previews#gatsby-plugin-prismic-previews) and previews are working just fine. However if you create a shareable link from the previewed document and share is with a non Prismic user the preview is not resolving.

**Logged in in Prismic**
Everything is working fine, previews and shareable links.

**Not logged in in Prismic**
Non published documents will show the 404 page and published documents won't show the edits.

**Versions**
gatsby: v3.7.2
gatsby-plugin-prismic-previews: v4.0.0-beta.18
gatsby-source-prismic: v4.0.0-beta.17

**Code**
```
// gatsby-config.js

module.exports = {
  plugins: [
    {
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: process.env.GATSBY_PRISMIC_REPOSITORY_NAME,
        accessToken: process.env.PRISMIC_ACCESS_TOKEN,
        customTypesApiToken: process.env.PRISMIC_CUSTOM_TYPES_API_TOKEN,
      },
    },
    {
      resolve: 'gatsby-plugin-prismic-previews',
      options: {
        repositoryName: process.env.GATSBY_PRISMIC_REPOSITORY_NAME,
        accessToken: process.env.PRISMIC_ACCESS_TOKEN,
        toolbar: 'new',
      },
    }
  ],
}
```

```
// gatsby-browser.js and gatsby-ssr.js

import React from 'react'
import { PrismicPreviewProvider } from 'gatsby-plugin-prismic-previews'
import { Reset } from 'styled-reset'

import 'gatsby-plugin-prismic-previews/dist/styles.css'

import { GlobalStyles } from './src/global-styles'

export const wrapRootElement = ({ element }) => <PrismicPreviewProvider>{element}</PrismicPreviewProvider>

// wrapPageElement needed for Styled Components
export const wrapPageElement = ({ element }) => (
  <>
    <Reset />
    <GlobalStyles />
    {element}
  </>
)

```

```
// preview.js

import React from 'react'
import { withPrismicPreviewResolver } from 'gatsby-plugin-prismic-previews'

import linkResolver from '../lib/link-resolver'

const PreviewPage = () => {
  return <div>loading preview...</div>
}

export default withPrismicPreviewResolver(PreviewPage, [
  {
    repositoryName: process.env.GATSBY_PRISMIC_REPOSITORY_NAME,
    linkResolver,
  },
])
```

```
// 404.js

import * as React from 'react'
import { withPrismicUnpublishedPreview, componentResolverFromMap } from 'gatsby-plugin-prismic-previews'

import linkResolver from '../lib/link-resolver'

import PageTemplate from '../templates/prismic-page'
import ArticleTemplate from '../templates/prismic-article'
import Layout from '../components/layout'

const NotFoundPage = () => {
  return (
    <Layout>
      <h1>404 Page not found</h1>  
    </Layout>
  )
}

export default withPrismicUnpublishedPreview(NotFoundPage, [
  {
    repositoryName: process.env.GATSBY_PRISMIC_REPOSITORY_NAME,
    linkResolver,
    componentResolver: componentResolverFromMap({
      page: PageTemplate,
      article: ArticleTemplate,
    }),
  },
])
```

**Comment by angeloashmore** [comment]
Hey @jordyvg, I think think might be expected based on your repository security settings. If a user is not logged in to your repository, the Prismic toolbar may not load as a privacy feature.

You could try out different Repository Security settings to see if that enables previews from non-logged-in users. You can find this setting in **Settings > API & Security**.

![image](https://user-images.githubusercontent.com/8601064/124813190-4d037b80-df00-11eb-8ee2-2dca7c9c3f2f.png)

**Comment by benjaminwaterlot** [comment]
Hello @angeloashmore, 

We've got the same problem here - shareable preview links only work if you're connected to Prismic, which defeat the purpose of generating a shareable link.

I tried switching the repository security to `Open API` with no success.

If I'm not mistaken, the shareable link is functionally identical to the actual URL of the resource you're sharing: you'll see the preview if you have the prismic preview cookie and you'll see published content if not.

**Comment by angeloashmore** [comment]
Hey @benjaminwaterlot, the share link from the Prismic Toolbar will give you a short link (looks like `https://prismic.link/abc123`).

That link will do the following:

1. Send you to a Prismic page that sets the preview cookie in the browser.
2. Redirects the user to the shared page on your site. Since the cookie is now present, the preview session will start.

Are you sharing the Prismic share link or just the page URL?

**Comment by kb1995** [comment]
@angeloashmore Just wanted to flag that I'm experiencing the same problem.

1. My Privacy Settings is Public API for master only
2. When I create a sharable link for a unpublished document and go in incognito/another browser, i get a 404
3. When I create a sharable link for a published document (with changes) and go in incognito/another browser, i get the published document.

From what I saw, the preview cookie is not being set in the browser. Is it working for you?

**Comment by benjaminwaterlot** [comment]
At our company we finally decided to stop using the preview feature of Prismic and instead use a `Staging` release, and set an env variable for our staging website to define the release which we should pull content from.

The preview feature has been 
* a bit too confusing for editors (they can't seem to be certain they are previewing published or preview content, and when they share the previews with important stakeholders depending on the publish status of the content and/or the fact that said stakeholders are logged-in, they see the content or they don't), 
* too unstable lately (with errors sometimes coming from the preview endpoint, sometimes from the plugin, sometimes from developer mistakes having forgotten to update code after a custom type change),
* overall too "magical" : no-one at the company is glad to ship preview-only code (the HoCs) and dependencies into production ; and having to do things like sizing images twice (because gatsbyImageData GraphQL arguments are stripped in preview) is worrying on a maintenance point of view.

I'd like for Prismic to allow a more simple preview feature, using something as simple as Gatsby Cloud's live preview which seems more reliable in my experience.

**Comment by angeloashmore** [comment]
Hey @benjaminwaterlot, sorry the preview setup didn't work well for you. In most cases, `gatsby-plugin-prismic-previews` works sufficiently for previews. For complex setups where you are using custom `gatsbyImageData` arguments and large GraphQL queries, Gatsby Cloud may be a better fit.

Because Gatsby is primarily a static site generator, there is no server to run Gatsby's GraphQL API during a preview. As a result, the preview plugin is limited in what it can support.

That's where Gatsby Cloud comes in: it is a running server that will update your site as content is edited in a Release. This has limitations as well, such as not being able to have multiple preview branches. Like you mentioned, however, it is more stable since it is backed by a full Gatsby build and server.

We have an updated guide describing how to integrate with Gatsby Cloud here: https://prismic.io/docs/technologies/prismic-gatsby-cloud

**Comment by kb1995** [comment]
@angeloashmore Sorry for the ping, but do you have any updates regarding the Shareable links? My client has been wanting to use it over the last 2 weeks in order to share blog posts with their internal team/clients

**Comment by angeloashmore** [comment]
I'm going to close this issue as share links are working, but please report here if this is not the case and I will reopen it.
