### ISSUE TITLE
Error on build: A valid fetch implementation was not provided.

### ISSUE THREAD

**Issue by nooxx** [prismicio/prismic-gatsby#437]
Hi, I've migrated from gatsby V2 to V3 and gatsby-source-prismic from V3 to V4.
Now when I start my local dev server or the build process, I get this error a few times:

![Screenshot 2021-08-30 at 16 11 39](https://user-images.githubusercontent.com/6512445/131357712-5a9618bf-e88e-4aa9-a271-bfa083619f1d.png)

Also when I go to http://localhost:8000/___graphql, I don't see any of my prismic custom types.
Looks like my prismic repo is not detected anymore.

### Versions

- gatsby-source-prismic: 4.1.2
- gatsby-plugin-prismic-previews: 4.1.2
- node: 14.16.1

### Reproduction

gatsby-config.js:
```
require(`dotenv`).config({
  path: `.env`,
})

module.exports = {
  pathPrefix: `/`,
  siteMetadata: {
    title: `Test`,
    description: `Test`,
    siteUrl: "https://test.com",
  },
  plugins: [
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: "gatsby-source-prismic",
      options: {
        repositoryName: 'testrepositor.cdn',
        accessToken: process.env.GATSBY_PRISMIC_TOKEN,
        linkResolver: (doc) => {
          return `/${doc.uid}`
        },
        htmlSerializer: () => {},
        schemas: {
          posts: require("./src/schemas/posts.json"),
          tags: require("./src/schemas/tags.json"),
          collections: require("./src/schemas/collections.json"),
          collectiontags: require("./src/schemas/collectiontags.json"),
          page: require("./src/schemas/page.json"),
        },
        shouldDownloadImage: () => {
          return true
        },
      },
    },
  ],
}
```

package.json:
```
{
  "scripts": {
    "build": "gatsby build",
    "start": "gatsby develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean"
  },
  "dependencies": {
    "dotenv": "^8.2.0",
    "gatsby": "^3.12.1",
    "gatsby-image": "^3.11.0",
    "gatsby-plugin-image": "^1.12.0",
    "gatsby-plugin-prismic-previews": "^4.1.2",
    "gatsby-plugin-sharp": "^3.12.0",
    "gatsby-source-prismic": "^4.1.2",
    "gatsby-transformer-sharp": "^3.12.0",
    "prismic-reactjs": "^1.3.4",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0"
  },
  "devDependencies": {
    "prettier": "^1.19.1",
    "url-loader": "^4.1.0"
  }
}
```

**Comment by angeloashmore** [comment]
Hi @nooxx, sorry you're experiencing this error. Does it happen every time you start the server?

Can you try the following?

- Remove the `shouldDownloadImage` plugin option ([see details](https://prismic.io/docs/technologies/gatsby-source-prismic-v3-to-v4#removeshoulddownloadfile))
- Remove the `htmlSerializer` plugin option if the function is empty
- Is `testrepositor.cdn` the name of your repository? The updated plugin will automatically use the CDN URL so you shouldn't include `.cdn` in the `repositoryName`

Hopefully this fixes your issue. Could you let me know if it works (or not) after those changes?

---

For some background information on the error, this happens when `@prismicio/client` doesn't have a `fetch` function to make network requests. `gatsby-source-prismic` will automatically provide one, but if the plugin options validation fails, then the default `fetch` is never passed.

This should be treated as a bug since the root cause of the error is hidden.

**Comment by nooxx** [comment]
Hi @angeloashmore, thank you! Doing all of this worked. (Yes it happened every time I start the server).

**Comment by angeloashmore** [comment]
@nooxx Great! Glad to hear it's working!

(I'm going to leave this issue open since there is an underlying issue that needs to be fixed.)

**Comment by angeloashmore** [comment]
V5 should fix this issue. If plugin options are invalid, it won't prevent `@prismicio/client` from getting a valid `fetch` function now.
