### ISSUE TITLE
Previews for unrelated documents break on null data with FIELD_VALUE_TYPE_PATH_MISMATCH_MSG

### ISSUE THREAD

**Issue by tjjjwxzq** [prismicio/prismic-gatsby#453]
### Versions

- gatsby-source-prismic: 4.1.2
- gatsby-plugin-prismic-previews: 4.1.3
- node: 16.1.0

### Reproduction

When content relationship fields are null due to improperly linked data in a certain document (and it seems, specifically when the content relationship is a newly added field to the custom type, for which there are pre-existing documents), previews break across the board, even for unrelated documents that are loaded on the same page (which I assume is because all documents are "loaded/processed" in a preview context, and have `refineFieldValue` run on their nodes, even if they are not the document under preview?)

This doesn't seem like desirable behaviour for two reasons:

1. I don't expect previews for a document to break because of null values in an unrelated document
2. I don't expect previews for a document to completely break because of type mismatches due to null values; isn't it Prismic philosophy that we can never assume that values will not be null, and thus should handle null failures gracefully? 

In my case, the documents render perfectly fine in non-preview mode, since I do a null-check and render a default value if the field is indeed null.

After some more investigation, it seems like null fields don't break once you have explicitly set it to some value and then set it back to null. I'm not entirely sure what's the difference when a new field is added to a custom type with pre-existing documents (and hence defaults to some kind of null value) vs. someone going in and explicitly removing the value on that field.

### Steps to reproduce

Create a custom type and  documents of that type. Then add a content relationship field to the custom type and don't update any of the documents.

Attempt to render the document, and the linked document based on that content relationship field, but with null check logic. 

To be more concrete, I have the following custom types set up:

Article, which has a slice zone that allows you to create Dividers, by linking to a Divider document with the corresponding type of Divider image. My code for rendering the dividers in an article is as follows (I check for null or empty object documents, and default to a default image if no divider document was linked):

```

export const ArticleDivider = ({ primary }) => {
  const { type } = primary
  const image =
    type.document && Object.keys(type.document).length !== 0 ? type.document.data.image : null

  return (
    <Divider
      type={image ? null : DividerType.DEFAULT}
      image={image}
      styles={{ ...theme.articlePageStyles.containedElement, my: 3 }}
    />
  )
}

ArticleDivider.propTypes = ArticleDividerPropTypes

``` 

I didn't really do a solid reproduction of the issue after I "fixed" it by explicitly updating the new content relationship field in my documents. Nonetheless I thought documenting this behaviour in this issue might be helpful in saving others from frustration when encountering a similar problem, and there is probably a way to prevent this weirdness from happening when a new field is added to custome types?

### What is expected?

Document previews don't break.

### What is actually happening?

When the new content relationship field is not updated, document previews break with the `FIELD_VALUE_TYPE_PATH_MISMATCH_MSG`, for the given problematic documents and for completely unrelated documents. (eg. although it was some of my article documents that were having the issue, previews for my Footer document were also broken; I wish I could provide a screenshot, but I neglected to take one when the problem surfaced and I ended up fixing the issue by explicitly updating the fields; the problem does not occur even when I explicitly remove the field's value now)

**Comment by angeloashmore** [comment]
@tjjjwxzq Thank you for providing a detailed report!

I understand what you're describing. I will do some tests and find a fix.

You are correct in assuming that all previews fail because all documents are processed even when previewing just one document. For some background info, the plugin does this because we need all documents during a preview in order to support content relationships. We can't just query and process the one document being previewed.

**Comment by angeloashmore** [comment]
@tjjjwxzq Here is what I tested:

1. Create a Custom Type with any field.
2. Create a document of that type.
3. Add a Link field to the Custom Type.
4. Go back to the document and preview it. Do not edit or publish any changes.

The preview works. The document will *not* have a data field for the new field (e.g. if you add a "my_link" field, "my_link" will not be a property within `data`).

Next, do this:

1. Make *any* change in the document, save, and publish. The change does not have to be for the new field.
2. Preview the document.

Now you will see the new link field is present within `data`, even if you did not edit it (e.g. if you add a "my_link" field, "my_link" will be a property within `data`).

**At this point _all_ documents of that type will contain the new field.**

This happens because publishing a new document version creates a new "ref" for your repository. You can think of it clearing the cache for all your documents and saving a version for them.

---

This is how you can trigger the `FIELD_VALUE_TYPE_PATH_MISMATCH_MSG` message.

1. Delete an existing field from a Custom Type. Do not edit any documents.
2. Restart your Gatsby server with the updated Custom Type.
3. Preview an existing document.

The `FIELD_VALUE_TYPE_PATH_MISMATCH_MSG` error will display since the document still contains the old field. Because the field was removed from the Custom Type, the plugin has no knowledge of the field.

Here's how you fix it:

1. Make *any* change in any document, save, and publish.

**At this point _all_ documents of that type will no longer contain the removed field.**

Just like before, this happens because publishing a new document version creates a new "ref" for your repository. You can think of it clearing the cache for all your documents and saving a version for them.

---

Does this address the issue you are experiencing? I was unable to reproduce exactly what you described, but the two scenarios I described above may be related.

**To reiterate**: Can you edit any document (you can just delete a character a re-type it) and publish it? All of your documents will use the updated Custom Type now.

**Comment by tjjjwxzq** [comment]
Thanks @angeloashmore for looking into it and the detailed test cases + underlying explanation of behaviour. I do think it was scenario 1 that broke for me even though you say that saving any document of a specific custom type should clear the cache for all documents of that custom type and previews should work thereafter. However, I was transitioning between `gatsby-plugin-prismic-preview` versions when this was happening; or more specifically, I had added the new field to the custom type while on an older version (v4.0.0-beta), and previews were working perfectly fine (and I definitely did save + publish some of the documents under that custom type), then upgraded to `v4.1.3`, after which I started encountering this error. So it could be very well be a bug that was occuring from the upgrade that required me to touch and save one of the documents again on the new version to rectify it.

Nonetheless give me some more time to confirm the behaviour again on the latest version, and if all is good and working as expected I'll close this issue :)
