### ISSUE TITLE
Error: Unable to serialize object as a key - Empty Embed Field

### ISSUE THREAD

**Issue by jodiedoubleday** [prismicio/prismic-gatsby#484]
### Versions

- gatsby-source-prismic: 5.2.2
- gatsby-plugin-prismic-previews: 5.2.1
- node: v14.17.3

### Reproduction

**_Minimal test repo to follow shortly (can give access to live repo if needed)_**

### Steps to reproduce
Running any project with an empty embed field causes builds to fail. In our case some embed fields for our content team are optional.

### What is expected?
The builds should continue with the video result in graphql being null for the video field.

### What is actually happening?
Build fail with the following error...
<img width="599" alt="Screenshot 2021-11-18 at 22 07 02" src="https://user-images.githubusercontent.com/778942/142506371-2512b330-39e0-4430-9d1a-a1ead0ef7219.png">

When running develop the graphql fails...
<img width="1118" alt="Screenshot 2021-11-18 at 22 15 29" src="https://user-images.githubusercontent.com/778942/142506422-b9120fc9-5566-41a3-825c-1e6e6260ad36.png">

**Comment by mikkosalo** [comment]
Same problem here. Cannot update to Gatsby 4 before this is fixed.

**Comment by angeloashmore** [comment]
Hey @jodiedoubleday and @mikkosalo,

Sorry for the delay in response. I'm catching up on issues now.

Can you update to `gatsby-source-prismic@v5.3.2` and try again?

## Background

This seems to be a result of the LMDB change in Gatsby 4. Rather, the change surfaced a bug that already existed.

gatsby-source-prismic infers fields for Embed fields because each oEmbed provider (e.g. YouTube, Vimeo, etc.) can provide its own set of fields. A YouTube embed may not include the same fields as a Vimeo embed, for example.

To do this, each Embed field is turned into a Gatsby Node. The Embed field is replaced with the string ID of that node. If the Embed field is left empty, however, the Embed field is left as is, which is `{}`. This causes LMDB and GraphQL to fail since it is expecting a string.

The latest update converts an empty Embed field from `{}` to `null`, which fixes the issue.

## Side note

If no embed fields are populated, Gatsby does not know which fields should be present. If this happens in your app, you can tell Gatsby which fields should be present using `createSchemaCustomization` in `gatsby-node.js`.


Example:

```js
// gatsby-node.js

/** @type import('gatsby').GatsbyNode['createSchemaCustomization'] */
exports.createSchemaCustomization = ({ actions, schema }) => {
  const { createTypes } = actions;
  const { buildObjectType } = schema;

  // List known embed fields. Any unknown fields will still be inferred.
  const PrismicEmbedType = buildObjectType({
    name: "PrismicEmbedType",
    fields: {
      height: "Int",
      embed_url: "String",
      thumbnail_url: "String",
      title: "String",
      type: "String",
      width: "Int",
    },
  });

  createTypes(PrismicEmbedType);
};
```

**Comment by mikkosalo** [comment]
Seems to work with `gatsby-source-prismic@v5.3.2`. Thank you very much!

**Comment by jodiedoubleday** [comment]
Thank you for the fix @angeloashmore  and great explanation!

**Comment by nanorepublica** [comment]
I am getting this error when trying to use an embed field with a youtube video present. One thing I am initially confused on is that the latest version of `gatsby-source-prismic` I can find (npm, releases on this repo) is `v5.2.6` is the above version specified of `v5.3.2` a typo and supposed to be `v5.2.3`?

gatsby-source-prismic: 5.2.6
gatsby-plugin-prismic-previews: 5.2.6
node: v16.13.0

I have also added the above code in my gatsby-node for specifying schema fields and still no luck.

**Comment by angeloashmore** [comment]
Hi @nanorepublica, you're correct, that was a typo. It should be `v5.2.3` as seen in the [changelog here](https://github.com/prismicio/prismic-gatsby/blob/dcc2d864d8750d818c9a1f660712bd4c62b47e04/CHANGELOG.md#523-2021-12-01). I edited the comment for anyone seeing this in the future.

Are you saying that when you have a field containing a YouTube video, the query fails? Would you be able to post the GraphQL error you see in the terminal?

**Comment by nanorepublica** [comment]
@angeloashmore any thoughts on this? I will try reproducing this in a demo repo today.

**Comment by nanorepublica** [comment]
Turns out an 'unlisted' youtube video caused this error to crop up. Using a public video worked perfectly
