### ISSUE TITLE
ERROR #85911 GRAPHQL

### ISSUE THREAD

**Issue by antonborysov** [prismicio/prismic-gatsby#502]
### Versions

- gatsby-source-prismic: 5.2.5
- gatsby-plugin-prismic-previews: N/A
- node: 16.13.2

### Reproduction

Receiving these errors while running **gatsby develop**

> ERROR #85911  GRAPHQL
> 
> There was a problem parsing
> "/Users/.../node_modules/gatsby-source-prismic/src/runtime/normalize.ts"; any GraphQL
> fragments or queries in this file were not processed.
> 
> This may indicate a syntax error in the code, or it may be a file type
> that Gatsby does not know how to parse.
> 
> File: node_modules/gatsby-source-prismic/src/runtime/normalize.ts

These errors show up for the following files:

> File: node_modules/gatsby-source-prismic/src/runtime/normalize.ts
> File: node_modules/gatsby-source-prismic/src/runtime/runtime.ts
> File: node_modules/@imgix/gatsby/src/modules/gatsby-plugin/createImgixGatsbyImageDataFieldConfig.ts
> File: node_modules/@imgix/gatsby/src/modules/gatsby-plugin/graphqlTypes.ts
> File: node_modules/@imgix/gatsby/src/modules/gatsby-transform-url/breakpoints.ts
> File: node_modules/@imgix/gatsby/src/modules/gatsby-plugin/typeBuilder.ts

Had last successful build about a week ago, hadn't changed anything since. Tried to downgrade node, npm, gatsby-source-prismic, but nothing seems to help. So I'm assuming that something's wrong with the package. Tried running it on my stage server where I get the same result.

The develop stage actually goes through these errors and the website successfully runs on localhost, but the build does not go through showing the same errors. Breaks on **extract queries from components** step.

Gatsby info:
<img width="421" alt="Screen Shot 2022-03-19 at 00 08 51" src="https://user-images.githubusercontent.com/25830178/159091795-777c65a8-22a7-4ab4-ae2c-18748fd71f97.png">

**Comment by angeloashmore** [comment]
Hey @antonborysov, just letting you know I have seen this error as well but the cause isn't known yet. If you need a quick workaround, you can go into `node_modules` and delete the following directories:

- `node_modules/gatsby-source-prismic/src/`
- `node_modules/@imgix/gatsby/src/`

This will have to be done anywhere the `gatsby develop` or `gatsby build` are run. This is a very temporary solution until the cause is found.

**Comment by angeloashmore** [comment]
This issue is stale and may be fixed in a recent version. Please update to the latest version and try again. If the issue continues to be a problem, please open a new issue. Thank you!

See the documentation for guides on updating to the latest versions: [Gatsby + Prismic Migration Guides](https://github.com/prismicio/prismic-gatsby/tree/main/docs#migration-guides)
