### ISSUE TITLE
No type for path

### ISSUE THREAD

**Issue by ThAlmighty** [prismicio/prismic-gatsby#512]
### Versions

- gatsby-source-prismic: 5.2.7
- gatsby-plugin-prismic-previews: 5.2.8
- node: 14.19.3

### Reproduction

We are running into a problem where if we've generated our static site including the custom type definitions, the preview will break if a custom type is updated after that update without rebuilding the website. 

This breaks our workflow quite a lot because when developers are building or adjusting slices, the content marketeers still need to be able to preview the website. Forcing content marketeers to wait everytime a developer add or edits a custom type is not ideal.

### Steps to reproduce
1. Build website with customTypes
2. Preview works just fin
3. Update a custom type without rebuilding the website
4. Previews are broken until website is rebuild

### What is expected?
If new properties in custom types are added, the preview should function as expected, the new values can be ignored for that specific build since there i  no code using these new properties.

### What is actually happening?
Prismic is hard enforcing all types to be defined in a scheme.

**Comment by angeloashmore** [comment]
This issue is stale and may be fixed in a recent version. Please update to the latest version and try again. If the issue continues to be a problem, please open a new issue. Thank you!

See the documentation for guides on updating to the latest versions: [Gatsby + Prismic Migration Guides](https://github.com/prismicio/prismic-gatsby/tree/main/docs#migration-guides)
