### ISSUE TITLE
Coordinate Fields are incorrectly defined as Non-nullable

### ISSUE THREAD

**Issue by TannerJuby1** [prismicio/prismic-gatsby#513]
### Versions

- gatsby-source-prismic: 5.2.2
- gatsby-plugin-prismic-previews: 5.2.1
- node: 16.13.2

### Steps to reproduce

- Create a Prismic Custom Type with a Coordinates Field
- Create a record of this type and don't set Coordinates
- Create a GraphQL query that queries for the coordinates

### What is expected?

I would expect Gatsby to be able to handle null values for all Prismic fields (except UID) given the fact that Prismic does not have a required feature for fields (except UID)

### What is actually happening?

I get an error saying `The field "PrismicGeoPointType.latitude" was explicitly defined as non-nullable via the schema customization API`.

**Comment by jodiedoubleday** [comment]
I resolbved this by adding an infer to my gatsby node:

```
exports.createSchemaCustomization = ({ actions, schema }) => {
  const { createTypes } = actions
  const { buildObjectType } = schema

  const PrismicGeoPointType = buildObjectType({
    name: 'PrismicGeoPointType',
    fields: {
      latitude: 'Float',
      longitude: 'Float'
    }
  })

  createTypes(PrismicGeoPointType)
}```

**Comment by angeloashmore** [comment]
This issue is stale and may be fixed in a recent version. Please update to the latest version and try again. If the issue continues to be a problem, please open a new issue. Thank you!

See the documentation for guides on updating to the latest versions: [Gatsby + Prismic Migration Guides](https://github.com/prismicio/prismic-gatsby/tree/main/docs#migration-guides)
