### ISSUE TITLE
SSR breaking link resolver functionality on builds

### ISSUE THREAD

**Issue by NeversSync** [prismicio/prismic-gatsby#516]
# Versions

- gatsby-source-prismic: v5.2.9
- gatsby-plugin-prismic-previews: 5.2.7
- node: v.14.17.0
- gatsby v4.17.0

### Steps to reproduce
1. Stand up a basic Prismic/Gatsby project with a basic link resolver. In a page component add and export a `getServerData` call to tell gatsby to SSR that page. 
2. In a Prismic document, add a link using the `link to document` option. Then, add another link using the `link to web` option. 
3. Write a query which queries for both link fields from the document you've created (uid, url specifically). Log out the data from that query in the page component. 
4. Start the local development server (`gatsby develop`), notice that url field is populated (see screenshot) for both link types
5. Run a local build (`gatsby build && gatsby serve`). Notice that the url field returned by link resolver is null (see screenshot) for `link to document` type links

### What is expected?
SSR should be supported and not result in a missing url field in builds or queries for any link types.

### What is actually happening?
When adding a `getServerData` call to a page component to leverage SSR and using a standard link resolver, url fields on links to documents are null on builds, but are populated as expected on development 
server runs. 

Package-json: [package-json.pdf](https://github.com/prismicio/prismic-gatsby/files/9245514/package-json.pdf)
Link resolver: [linkresolver.pdf](https://github.com/prismicio/prismic-gatsby/files/9245519/linkresolver.pdf)
Local development link fields console logs: 
[local-development-link-logs.pdf](https://github.com/prismicio/prismic-gatsby/files/9245522/local-development-link-logs.pdf)
Local build link fields console logs: [local build link logs.pdf](https://github.com/prismicio/prismic-gatsby/files/9245525/local.build.link.logs.pdf)

**Comment by NeversSync** [comment]
Made some progress and added a comment with a follow up issue/question here: https://github.com/prismicio/prismic-gatsby/pull/479#issuecomment-1213594878

**Comment by angeloashmore** [comment]
Hey @NeversSync, thanks for the report. I'm having trouble recreating the issue, but I think I have an idea of what the underlying issue is.

Basically, when Gatsby is in SSR mode, it doesn't always have access to the full options given to a plugin. If an option is not serializable, such as a function, it is not accessible in all areas of the plugin. Since Link Resolvers are functions, the plugin may not have access to the Link Resolver, resulting in `null` URLs.

When you use Route Resolver (the `routes` option) instead of Link Resolver, you are providing an object rather than a function. The object is serializable, thus is always available. It also embeds the resolved URLs directly into the Prismic API responses at build time, so there is no URL resolution happening at request time.

I don't have and answer/solution to share right now, but I'll continue to test this.

**Comment by NeversSync** [comment]
@angeloashmore Thank you for the response, I have just resolved the issue. 

The fix:
Use a combination of the Link Resolver and the Route Resolver in the gatsby config options. I also needed to include the fetchLinks option for one document path which has an optional subpath based on a Content Relationship field (i.e. website.com/{optional category}/{uid}.  Lastly, I am including the exact same `routes` option for the options in `gatsby-plugin-prismic-previews`, but not the link resolver or fetchLinks option as it doesn't seem required. Let me know if you think this is the right approach. 

Another aspect that was required for the fix was learning that a `UID` was required on the Content Relationship field for urls to resolve correctly in the Route Resolver, I did not that field and it was throwing an `Invalid API Response` error and a 500 if I directly tried to hit the endpoint. Maybe it would be helpful to make this error messaging more explicit and helpful?

In general, this felt like a case of lacking documentation. I barely found any docs on how to implement the Route Resolver within the plugin config, and no mention of details such as the required UID for Content Relationship Fields. Thank you again for your help and work on this project!
