### ISSUE TITLE
Hyperlinks inside Rich Text fields have target="undefined"

### ISSUE THREAD

**Issue by PietroAimone** [prismicio/prismic-gatsby#519]
### Versions

- gatsby-source-prismic: 5.2.9
- gatsby-plugin-prismic-previews: 5.2.8
- node: 16.14.2

<details open>
<summary>Not sure if this is the right place to post this. We've recently upgraded the plugin from 2.3.0-alpha.3 to 5.2.9, and every single Rich Text field in our application that contained a hyperlink with "Open in new tab" unchecked is now being returned with target="undefined" by the Prismic API. Chrome interprets this as "target="_Blank", so we have no way of having links that open in the same page.
</summary>
</details>

Here is our [package.json](https://github.com/prismicio/prismic-gatsby/files/9573842/package.json.txt)

### Steps to reproduce
- Pick any Slice with a Rich Text field and put a hyperlink to the web inside it, with "Open in new tab" unchecked.
- Query the field in GraphQL and notice how the "html" field will appear as: 
`<a href=\"www.github.com\" target=\"undefined\" rel=\"noopener noreferrer\">Hyperlink text</a>`

### What is expected?
If "Open in new tab" is unchecked, i would expect the "html" field of the Rich Text to contain the hyperlink with target="_self" or no target property at all.

### What is actually happening?
the "html" field of the Rich Text to contains the hyperlink with target="undefined", which Chrome interprets as target="_blank".

**Comment by angeloashmore** [comment]
Hi @PietroAimone, thanks for the report! Yes, this is the correct place to report bugs with the Gatsby plugin.

The issue comes from `@prismicio/helpers`, which was just updated to fix this issue here: prismicio/prismic-helpers#59.

The Gatsby plugins have been updated to include that fix as of the following versions:

- `gatsby-source-prismic`: `v5.2.10`
- `gatsby-plugin-prismic-previews`: `v5.2.10`

You can update to the latest versions with the following command:

```sh
npm install gatsby-source-prismic@latest gatsby-plugin-prismic-previews@latest
```

If that doesn't fix the issue, please let me know and I'll take another look. Thanks!

**Comment by PietroAimone** [comment]
I updated the plugins and the problem was resolved.
Thank you very much for the help!

**Comment by angeloashmore** [comment]
You’re welcome! Happy to hear that!
