### ISSUE TITLE
TypeError: A dynamic import callback was not specified. (value)

### ISSUE THREAD

**Issue by leomitimiti** [prismicio/prismic-gatsby#521]
### Versions

- gatsby-source-prismic: 6.0.0-alpha.17
- node: v16.15.0
- gatsby: v4.4.0
### Reproduction

<details open>
<summary>Additional Details</summary>
<br>
Gatsby displays the error:
TypeError: A dynamic import callback was not specified. (value)
and the application does not run
</details>

### What is actually happening?
![image](https://user-images.githubusercontent.com/102228632/200704938-89ceabdf-891a-4dde-9af2-07927ae8d353.png)

**Comment by leoperez** [comment]
@angeloashmore how could be this resolved?

**Comment by angeloashmore** [comment]
@leomitimiti @leoperez Are you able to share a reproduction of this error? This isn't something I've seen before, and it seems to be directly from Node, not Gatsby's code.

Could you also share your `package.json`? Thanks!

**Comment by leomitimiti** [comment]
@angeloashmore  This is my package.json

[package.json.txt](https://github.com/prismicio/prismic-gatsby/files/9997690/package.json.txt)

**Comment by pvpg** [comment]
@leomitimiti I got the same err and solved it by updating `react` and `react-dom` to the latest version

**Comment by angeloashmore** [comment]
This issue is stale and may be fixed in a recent version. Please update to the latest version and try again. If the issue continues to be a problem, please open a new issue. Thank you!

See the documentation for guides on updating to the latest versions: [Gatsby + Prismic Migration Guides](https://github.com/prismicio/prismic-gatsby/tree/main/docs#migration-guides)
