### ISSUE TITLE
Unable to generate build with gatsby-source-prismic package 

### ISSUE THREAD

**Issue by sandeep-groot** [prismicio/prismic-gatsby#524]
When I try to integrate gatsby-source-prismic package with gatbsy version: 3.0.0-next.0, I am getting this error.
 Error: **Your plugins must export known APIs from their gatsby-node.js.**

I tried to upgrade gatsby version to latest but still there is issue while generation build on gatsby cloud.
If I try to upgrade gatsby version to latest then it throws this error:
**Failed to compile: Error: Command failed with exit code 1: npm install --unsafe-perm --prefer-offline --no-audit --registry=https://registry.npmjs.org/**

Although, local deployment works fine when we run "gatsby develop", but seems to have an issue when we try to build it on gatsby cloud/netlify.

**Comment by angeloashmore** [comment]
This issue is stale and may be fixed in a recent version. Please update to the latest version and try again. If the issue continues to be a problem, please open a new issue. Thank you!

See the documentation for guides on updating to the latest versions: [Gatsby + Prismic Migration Guides](https://github.com/prismicio/prismic-gatsby/tree/main/docs#migration-guides)
